### PR TITLE
Update for latest forge for 1.10.2 and stable mappings

### PR DESCRIPTION
**Pull request by jriwanek**
Pretty simple patch, does what it says on the tin.

### CODE REVIEW

**Comment by bonii-xx** [comment]
You have a mappings property defined, but it's not actually used anywhere?

**Comment by jriwanek** [comment]
It's used by forge itself to set the version of MCP mappings used, give it a try by changing it to something random, it affected things here, hence how I know it works.

**Comment by jriwanek** [comment]
Also see:
https://github.com/SlimeKnights/Mantle/blob/master/build.gradle#L91
^ Specifically where that property is used.

**Comment by bonii-xx** [comment]
Yeah, I know it's set but not used in our build.gradle. Wasn't sure if FG uses it or not.

**Pull request merged**
