### PR TITLE
Update GuiManual.java

### PR DESCRIPTION
**Pull request by KosmosPrime**
Fix for issue #1560 in TConstruct.
https://github.com/SlimeKnights/TinkersConstruct/issues/1560

### CODE REVIEW

**Comment by bonii-xx** [comment]
Dang, I wanted to comment on this when I read it but then forgot. Well better late than never: Changing rendering flags like that can be very dangerous. Just one small little change can cause to many edge cases where it doesn't work. The issue with the overall problem is not Mantle/Tinkers too, so changing this will only lead to new rendering errors with other mods.

**Comment by KosmosPrime** [comment]
I think not enabling blending before rendering an image with alpha (e.g. text) is very much so a problem in Mantle/TConstruct. It might be annoying that some other mod does not put the OGL context back to how it was... but none of the classes in Mantle are doing that, so pointing your finger at that other mod is not fair.

**Comment by bonii-xx** [comment]
So by your logic we should add even more code that works perfectly fine in a normal environment and that will most likely break some rendering things because it sadly exists in some other places?

**Comment by KosmosPrime** [comment]
It does not break anything. This change enables alpha, a texture without it will not be affected in any way.

**Comment by JosephDMC** [comment]
Where do I add this fix?

**Comment by Adaptivity** [comment]
Never happen to me previously until yesterday -_- People saying this is mapwriter thing, yes I have mapwriter 2. Anyway, looking for a fix, to this or another.

**Comment by progwml6** [comment]
A specific combination of mods along with steps to reproduce would be helpful

**Comment by Adaptivity** [comment]
Steps to reproduce:
1. Install Mantle 0.3.2.jenkins187
2. Install Tinkers Construct 1.8.6a
3. Install [MapWriter 2](http://minecraft.curseforge.com/mc-mods/231387-mapwriter-2)
4. Go into the world
5. Get Material and You: Volume 2
6. Open page 2 or 3
7. ???
8. Strange characters appeared
Removing mapwriter fixes the problem, reproduced on Forge 1481 and Java 8 update 45

**Comment by Adaptivity** [comment]
anything about it?

**Comment by Adaptivity** [comment]
Maybe pull this? Then I can test this and if this breaks something or doesn't fix the problem you can revert this? Anyway, fix will be available only on Jenkins so this will not be available to the public.

**Comment by KosmosPrime** [comment]
You can test it with this class file: https://www.dropbox.com/s/58w8t4e3l48ybku/GuiManual.class?dl=0
Replace the one in mantle.jar/mantle/client/gui with this one (made with a bytecode editor).

**Pull request merged**
