### PR TITLE
1.19.3

### PR DESCRIPTION
**Pull request by queengooborg**
This PR ports Mantle from 1.19.2 to 1.19.3.  While Mantle has already been ported to 1.20.1, the motivation behind this is to perform a gradual porting of Tinkers' Construct to 1.19.3, then 1.19.4.

Note: this sets the version number to 1.11, but this version number is already picked for the 1.20.1 version of Mantle.
Recommended: this PR should be landed to its own dedicated branch, rather than onto the 1.19 branch.

### CODE REVIEW

**Comment by KnightMiner** [comment]
I have no plans to support 1.19.3. That version is dead.

I also have no plans to support 1.19.4. I don't have time to port to a version that I will just immediately abandon, and not every change needed for 1.19.3 or 1.19.4 carries over to 1.20.1.

----

I really recommend you talk to me before taking large actions such as making a PR to port something. A few minutes of talking can save hours of wasted work.

**Comment by queengooborg** [comment]
No, not every change is going to carry over to 1.20.1, but most do -- in fact, the majority of changes made in this PR were, in fact, backported from the 1.20 branch.

My intent for this process was to simplify the process for https://github.com/SlimeKnights/TinkersConstruct/pull/5258 in the long run.  The philosophy behind this approach is that, as far as I can tell, each of the last few versions of Minecraft (1.19.3, 1.19.4 and 1.20[.1]) introduced a large API change, and it is much easier to work on/review smaller chunks over time, rather than one large chunk all at once.  While there were some changes that won't be ported over to 1.20.1 (for example, the sound effects), the diff of this PR is actually shockingly similar to that of the 1.19 <-> 1.20 branches.

In creating this PR, it also helped me figure out some of the changes needed to port Tinkers' Construct to newer versions, so I could help https://github.com/SlimeKnights/TinkersConstruct/pull/5258 progress further.  So, I don't feel that this was a waste at all, even if it won't be merged.  Even if it's just for the purpose of learning, I'm happy that I had worked on this.  :)

**Comment by KnightMiner** [comment]
To be honest, if the port is so much work that you need to do it in multiple steps, it really will just be easier for me to do it myself. As I've told you before, I'm not not porting, I simply have not had time to do it. And reviewing a PR to port is nearly the same level of time commitment (especially if it does not even compile)

It's why when people asked to help port, I recommended concrete tasks that weren't just port the whole thing. But apparently people would rather do their own thing.

**Comment by queengooborg** [comment]
Well, the compiler failures and the effort it would take to review the porting process is exactly the reason _why_ I was trying to break it up into multiple steps.

I totally understand limited time, and especially the time it takes to review someone else's work.  But players are eager to see Tinkers' Construct on newer versions of Minecraft, and some (like myself) are so eager that they're willing to put in the effort to make that possible.  They have done the research needed in order to make the appropriate changes, so that others (like the project maintainers) wouldn't have to.

**Comment by KnightMiner** [comment]
The research is not the hurdle to clear. I already know what needs to be done; I've been watching Forge and Neo for a long time. Mostly its just I need quite a few consecutive hours to get it done, which I won't have for at least another week or two at earliest.

A good small PR can be reviewed in a few stages with only requiring around 15-30 minutes to review. A giant PR that touches thousands of files is back to several consecutive hours to review properly.

**Pull request closed without merging**
