### PR TITLE
jar tasks gets finalized by reobfJar task

### LINKED ISSUE #94: [1.11 (+?)] Modifierless jar on Maven is deobfuscated!
The normal jar on the maven is deobfuscated, causing all kinds of problems when used in a dev env with a different mapping!

I suggest adding
```Groovy
jar {
    // Do whatever you need here...

    finalizedBy reobfJar
}
```
to your `build.gradle`.

Also see MinecraftForge/ForgeGradle#440

I don't know which versions this affects though. Might be a lot though.

### PR DESCRIPTION
**Pull request by BrainStone**
- Fixed #94

### CODE REVIEW

**Comment by BrainStone** [comment]
This commit should be able to be cherry picked into all branches.

**Comment by progwml6** [comment]
PR this to the 1.11 and 1.12 branches a 6 line patch is not worth cherry picking

**Comment by BrainStone** [comment]
Will be separte PRs though. Is that ok?

**Comment by bonii-xx** [comment]
Yup.

**Comment by BrainStone** [comment]
You guys want me to make the same change over on TiC too?

**Comment by bonii-xx** [comment]
Yes please.

**Comment by BrainStone** [comment]
It would be great if you could make a new build for 1.11.2 that pushes this fix, so I can use it in my dev env. 👍

**Comment by bonii-xx** [comment]
Try 1.2.0.28

**Comment by BrainStone** [comment]
Just saw it. Thanks!

**Pull request closed without merging**
